# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cek.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
from PyQt5.QtGui import QPixmap
from io import BytesIO

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 691, 521))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.button_rest = QtWidgets.QToolButton(self.groupBox)
        self.button_rest.setGeometry(QtCore.QRect(0, 450, 111, 61))
        self.button_rest.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.button_rest.setObjectName("button_rest")
        self.button_tutup = QtWidgets.QPushButton(self.groupBox)
        self.button_tutup.setGeometry(QtCore.QRect(150, 450, 121, 61))
        self.button_tutup.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.button_tutup.setObjectName("button_tutup")
        self.edit_input = QtWidgets.QLineEdit(self.groupBox)
        self.edit_input.setGeometry(QtCore.QRect(10, 70, 241, 51))
        self.edit_input.setText("")
        self.edit_input.setObjectName("edit_input")
        self.button_browse = QtWidgets.QPushButton(self.groupBox)
        self.button_browse.setGeometry(QtCore.QRect(290, 70, 121, 51))
        self.button_browse.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.button_browse.setObjectName("button_browse")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(0, 1, 681, 61))
        self.textBrowser.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(220, 20, 261, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_image = QtWidgets.QLabel(self.groupBox)  # Mengganti QTextBrowser menjadi QLabel
        self.label_image.setGeometry(QtCore.QRect(20, 130, 221, 281))  # Atur geometri QLabel sesuai kebutuhan
        self.label_image.setStyleSheet("background-color: rgb(178, 178, 178);")
        self.label_image.setObjectName("label_image")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_2.setGeometry(QtCore.QRect(300, 140, 131, 201))
        self.textBrowser_2.setObjectName("textBrowser_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.button_tutup.clicked.connect(MainWindow.close) # type: ignore
        self.button_browse.clicked.connect(self.display_image)
        self.button_rest.clicked.connect(self.edit_input.clear)
        self.button_rest.clicked.connect(self.label_image.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def display_image(self):
        # Ambil URL dari QLineEdit
        url = self.edit_input.text()
        
        try:
            # Ambil gambar dari URL
            response = requests.get(url)
            image = QPixmap()
            image.loadFromData(response.content)  # Menggunakan response.content secara langsung

            # Tampilkan gambar di QLabel
            self.label_image.setPixmap(image)
            
            # Ambil ukuran gambar
            width = image.width()
            height = image.height()
            
            # Tampilkan ukuran gambar di QTextBrowser_2
            self.textBrowser_2.setHtml(f"""
                <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
                <html><head><meta name="qrichtext" content="1" /><style type="text/css">
                p, li {{ white-space: pre-wrap; }}
                </style></head><body style=" font-family:'MS Shell Dlg 2'; font-size:8pt; font-weight:400; font-style:normal;">
                <p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">
                <span style=" font-size:14pt; font-weight:600;">Width :</span> {width}</p>
                <p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">
                <span style=" font-size:14pt; font-weight:600;">Height :</span> {height}</p>
                </body></html>""")
                
        except Exception as e:
            print(f"Error loading image: {e}")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_rest.setText(_translate("MainWindow", "Reset"))
        self.button_tutup.setText(_translate("MainWindow", "Tutup"))
        self.button_browse.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "IMAGE PROCESSING"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Width :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">-</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Height :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">-</span></p></body></html>"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
